
test_user:
    resource: "@TestUserBundle/Resources/config/routing.yml"
    prefix:   /user

test_big:
    resource: "@TestBigBundle/Resources/config/routing.yml"

test_blog:
    resource: "@TestBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: TestUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout